trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    node --check server.js
  displayName: "Validate Node.js syntax"

- script: |
    python -m pip install --upgrade semgrep
    semgrep scan --config auto --error .
  displayName: 'SAST - Semgrep'

- script: |
    docker run --rm \
      -v $(Build.SourcesDirectory):/project \
      aquasec/trivy fs \
      --scanners vuln,misconfig,secret \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      /project
  displayName: 'SCA, Secrets and Misconfiguration Scan - Trivy'

- script: |
    docker build -t secure-node-app:latest .
  displayName: 'Build Docker image'

- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      aquasec/trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      secure-node-app:latest
  displayName: 'Container Vulnerability Scan'
